//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Anonimo_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Anonimo_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\4\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
  
    ViewBag.Title = "Jogar anonasdo";
    Layout = "~/Views/Shared/_DuvidoLayoutPage.cshtml";


#line default
#line hidden

#line 2 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\4\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
                        using (Html.BeginForm("Index", "CriarSalas",fo

  {
        {
                            {

#line default
#line hidden

#line 3 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\4\Duvido\Duvido.ASP-NET\Views\Duvido
Anonimo.cshtml"
                                      
                             }

#line default
#line hidden

#line 4 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\4\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
771A70D\4\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
771A70D\4\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
                                if (Model != null && Model.NomesAvatares != nu44444444474.NomesAvatares.5ount > 0)
                                {
               5                    

#line default
#line hidden

#line 5 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\4\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
                                        foreach (var avatar in 55555555585Avatares)
    6                                   {
                       6                    

#line default
#line hidden

#line 6 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\4\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml66666666696               7                                                             7     __o = avatar;


#line default
#line hidden

#line 7 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\4\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
                                        77777777707               8                                                             8     __o = avatar;


#line default
#line hidden

#line 8 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\4\Duvido\Duvido.ASP-NET\Views\Duvido\A88888888818ml"
          9                                       
                    9                   }

#line default
#line hidden

#line 9 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\4\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
                                          
                                }
99999999929              110    else
                                {
               10                   

#line default
#line hidden

#line 10 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\4\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.csh111111111030              11                                              
            11                  }

#line default
#line hidden

#line 11 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\4\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
                                if (!string.111111111141y(ViewBag.Erro12essage))
                                {
               12                   

#line default
#line hidden

#line 12 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\4\Duvido111111111252NET\Views\Duvi13\Anonimo.cshtml"
                                  __o = Vi13Bag.ErrorMessage;


#line default
#line hidden

#line 13 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\4\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
                                                                
                                }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Anonimo_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Anonimo_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\3\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
  
    ViewBag.Title = "Jogar anonasdo";
    Layout = "~/Views/Shared/_DuvidoLayoutPage.cshtml";


#line default
#line hidden

#line 2 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\3\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
                        using (Html.BeginForm("Index", "CriarSalas", FormMethod.Post))
                            {

#line default
#line hidden

#line 3 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\3\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
                                      
                             }

#line default
#line hidden

#line 4 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\3\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
                                if (Model != null && Model.NomesAvatares != null && Model.NomesAvatares.Count > 0)
                                {
                                    

#line default
#line hidden

#line 5 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\3\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
                                        foreach (var avatar in Model.NomesAvatares)
                                        {
                                            

#line default
#line hidden

#line 6 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\3\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
                                                                                           __o = avatar;


#line default
#line hidden

#line 7 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\3\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
                                                                                                                                      __o = avatar;


#line default
#line hidden

#line 8 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\3\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
                                                  
                                        }

#line default
#line hidden

#line 9 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\3\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
                                          
                                }
                                else
                                {
                                    

#line default
#line hidden

#line 10 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\3\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
                                                                    
                                }

#line default
#line hidden

#line 11 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\3\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
                                if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
                                {
                                    

#line default
#line hidden

#line 12 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\3\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
                                  __o = ViewBag.ErrorMessage;


#line default
#line hidden

#line 13 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\3\Duvido\Duvido.ASP-NET\Views\Duvido\Anonimo.cshtml"
                                                                
                                }

#line default
#line hidden
}
}
}
