//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__DuvidoLayoutPage_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__DuvidoLayoutPage_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\4\Duvido\Duvido.ASP-NET\Views\Shared\_DuvidoLayoutPage.cshtml"
              __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\4\Duvido\Duvido.ASP-NET\Views\Shared\_DuvidoLayoutPage.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\4\Duvido\Duvido.ASP-NET\Views\Shared\_DuvidoLayoutPage.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\4\Duvido\Duvido.ASP-NET\Views\Shared\_DuvidoLayoutPage.cshtml"
       __o = RenderBody();


#line default
#line hidden

#line 5 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\4\Duvido\Duvido.ASP-NET\Views\Shared\_DuvidoLayoutPage.cshtml"
   __o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 6 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\4\Duvido\Duvido.ASP-NET\Views\Shared\_DuvidoLayoutPage.cshtml"
   __o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__DuvidoLayoutPage_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__DuvidoLayoutPage_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\3\Duvido\Duvido.ASP-NET\Views\Shared\_DuvidoLayoutPage.cshtml"
              __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\3\Duvido\Duvido.ASP-NET\Views\Shared\_DuvidoLayoutPage.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\3\Duvido\Duvido.ASP-NET\Views\Shared\_DuvidoLayoutPage.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\3\Duvido\Duvido.ASP-NET\Views\Shared\_DuvidoLayoutPage.cshtml"
       __o = RenderBody();


#line default
#line hidden

#line 5 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\3\Duvido\Duvido.ASP-NET\Views\Shared\_DuvidoLayoutPage.cshtml"
   __o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 6 "C:\Users\gabza\AppData\Local\Temp\BF3F0E207C16CBB768BE62A23EFE1771A70D\3\Duvido\Duvido.ASP-NET\Views\Shared\_DuvidoLayoutPage.cshtml"
   __o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden
}
}
}
